name: toolofna-gaussian_splatting
channels:
  - defaults
  - conda-forge
  - nvidia/label/cuda-11.8.0

dependencies:
  - python==3.10
  - cuda-toolkit
  - cudnn
  - ffmpeg
  - pip
  - pip:
      - -r requirements_cuda118.txt
